name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: unbuntu-latest

    steps:
      name: Checkout code
      uses: actions/checkout@v4

      name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

      name: install dependencies
      run: pip install -r requirements.txt

      name: Run tests
      run: pytest --maxfall=1 --disable-warnings -q
